config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes, except: %i[index show new]
  resources :money_transactions, except: %i[index]
  resources :categories, except: [:index]
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :people
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'pages#home'

  get '/charts', to: 'charts#index'
end

app/controllers/money_transactions_controller.rb
# frozen_string_literal: true

class MoneyTransactionsController < ApplicationController
  before_action :set_money_transaction, only: %i[show edit update destroy]
  before_action :set_person_category, only: [:destroy]
  before_action :set_person_created_for, only: %i[create update]

  # GET /transactions or /transactions.json
  def index; end

  # GET /transactions/1 or /transactions/1.json
  def show
    @person = Person.find(PersonCategory.find(@money_transaction.person_category_id).person_id)
    @category = Category.find(PersonCategory.find(@money_transaction.person_category_id).category_id)
    @note = @money_transaction.note
  end

  # GET /transactions/new
  def new
    @people = current_user.people
    @money_transaction = MoneyTransaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @money_transaction = MoneyTransaction.new(money_transaction_params)
    create_note(@money_transaction, params.values[1][:body])
    if @money_transaction.save
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    create_note(@money_transaction, params.values[2][:body]) unless @money_transaction.note
    if @money_transaction.update(money_transaction_params)
      flash[:notice] = 'Transaction was successfully updated.'
      redirect_to money_transaction_path(@money_transaction)
    else
      render :edit
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @money_transaction.destroy
    respond_to do |format|
      format.html { redirect_to person_path(@person), notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # create note
  def create_note(transaction, body)
    note = Note.new(body: body)
    if note.valid?
      transaction.note = note
    else
      flash[:alert] = 'Note was not saved, maybe it was invalid'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_money_transaction
    @money_transaction = MoneyTransaction.find(params[:id])
    return if current_user == @money_transaction.person_category.person.user

    flash[:alert] = 'You must be owner of this transaction'
    redirect_to root_path
  end

  # Only allow a list of trusted parameters through.
  def money_transaction_params
    params.require(:money_transaction).permit(:amount_value, :person_category_id, :important)
  end

  def set_person_category
    @person = current_user.people.find(@money_transaction.person_category.person_id)
  end

  def set_person_created_for
    @person = Person.find(PersonCategory.find(money_transaction_params[:person_category_id]).person_id)
  end
end

app/views/money_transactions/_form.html.erb
<div class="col-6">
  <%= form_with(model: @money_transaction) do |form| %>
    <% if @money_transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@money_transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

        <ul>
          <% @money_transaction.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row mb-3">
      <%= form.label :amount_value %>
      <%= form.number_field :amount_value, class: "form-control" %>
    </div>
    <% if @money_transaction.new_record?%>
      <div class="form-group row mb-3">
        <%= form.label 'Category'%>
        <%= form.select(:person_category_id, options_for_select(PersonCategory.where(person_id: @people).order(:person_id).map { |pc| [pc.select_title, pc.id]}), {}, {required: true, class: "form-control"}) %>
      </div>
      <div class="form-group row mb-3">
        <%= form.label 'Text your note' %>
        <%= form.text_field :body, class: "form-control" %>
      </div>
    <% else %>
      <% if !@money_transaction.note %>
        <div class="form-group row mb-3">
          <%= form.label 'Text your note' %>
          <%= form.text_field :body, class: "form-control" %>
        </div>
      <% end %>
        <div class="form-group row mb-3">
          <%= form.hidden_field :person_category_id %>
        </div>
    <% end%>

    <div class="form-group row mb-3 col-3">
      <%= form.label 'Is it important?'%>
      <%= form.select(:important, [ ['Yes', true], ['No', false]], {}, {required: true, class: "form-control"}) %>
    </div>

    <div class="form-group row mb-3 justify-content-start">
      <%= form.submit class: "btn btn-outline-success col-4" %>
    </div>
  <% end %>
</div>

app/views/money_transactions/_transaction.html.erb
<h1 class="mb-3"> Transaction details </h1>
<div class="row">
    <div class="col-6">
      <div class="card mb-3 text-center">
        <h5 class="card-header"><%= @person.name %> - <%= @money_transaction.amount_value %> EUR</h5>
        <div class="card-body">
          <h5 class="card-title"><%= @category.name %> - <%= @category.transaction_type %></h5>
          <% if @note %>
            <p class="card-text">Note: <%= @note.body%></p>
            <%= link_to "Edit note", edit_note_path(@note) %> |
            <%= link_to "Delete note", note_path(@note), method: :delete, data: { confirm: "Are you sure?" } %>
          <% else %>
            No notes yet...  
          <%end%>
        </div>
        <div class="card-footer text-muted">
          Created: <%= @money_transaction.created_at %>
        </div>
      </div>
      <div class="transaction_btns">
        <%= link_to 'Edit transaction', edit_money_transaction_path(@money_transaction) %> |
        <%= link_to 'Back to person transaction list', person_path(@money_transaction.person_category.person_id) %>
      </div>
    </div>   
</div>

app/views/money_transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back to transaction', @money_transaction %> 

app/views/money_transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form'%>

<%= link_to 'Back to people', people_path %>

app/views/money_transactions/show.html.erb
<%= render 'transaction' %>