config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes, except: %i[index show new]
  resources :money_transactions, except: %i[index]
  resources :categories, except: [:index]
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :people
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'pages#home'

  get '/charts', to: 'charts#index'
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  has_one :money_transaction, dependent: :nullify
  validates :body, presence: true, length: { minimum: 2, maximum: 50 }
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[edit update destroy]
  before_action :set_transaction, only: %i[update destroy]

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to money_transaction_path(@money_transaction), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to money_transaction_path(@money_transaction), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
    transaction = MoneyTransaction.find_by(note: @note)
    return if current_user == transaction.person_category.person.user

    flash[:alert] = 'You must be owner of this note'
    redirect_to root_path
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:body)
  end

  def set_transaction
    @money_transaction = @note.money_transaction
  end
end

app/views/notes/_form.html.erb
<div class="col-6">
  <%= form_with(model: note) do |form| %>
    <% if note.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

        <ul>
          <% note.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row mb-3">
      <%= form.label :body %>
      <%= form.text_field :body, class: "form-control", placeholder: "Enter text here...", autofocus: true %>
    </div>

    <div class="form-group row mb-3 justify-content-start">
      <%= form.submit class: "btn btn-outline-success col-4"%>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back to transaction', money_transaction_path(@note.money_transaction)%> 

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>