config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes, except: %i[index show new]
  resources :money_transactions, except: %i[index]
  resources :categories, except: [:index]
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :people
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'pages#home'

  get '/charts', to: 'charts#index'
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  belongs_to :user
  has_many :person_categories, dependent: :destroy
  has_many :categories, through: :person_categories
  validates :name, presence: true,
                   length: { minimum: 2, maximum: 25 }

  before_create :check_uniqueness
  before_destroy :check_people_count

  private

  def check_people_count
    throw(:abort) if user.people.count <= 1
  end

  def check_uniqueness
    throw(:abort) if user.people.exists?(name: name)
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :create_person, only: [:create]
  after_action :create_default_category, only: [:create]

  # GET /people or /people.json
  def index
    @people = current_user.people
  end

  # GET /people/1 or /people/1.json
  def show
    @categories = @person.categories
    @person_categories = @person.person_categories
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    respond_to do |format|
      if @person.save
        format.html { redirect_to people_path, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        flash.now[:alert] = 'Something went wrong'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    if @person.destroy
      respond_to do |format|
        format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to people_url, alert: 'Sorry, but you cannot delete all people' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
    return if current_user == @person.user

    flash[:alert] = 'You must be the owner of this person'
    redirect_to people_path
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:name, :user_id)
  end

  def create_person
    @person = Person.new(person_params)
  end

  def create_default_category
    @person.categories << current_user.people.first.categories.first
  end
end

app/views/people/_categories.html.erb
<% if obj.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Transactions <sup>*</sup></th>
        <th scope="col"> Total summ<th>
      </tr>
    </thead>
    <tbody>
      <% obj.each do |person_category|%>
      <tr>
        <td>
          <div class="badge rounded-pill <%= person_category.category.transaction_type == 'Debit' ? 'bg-success' : 'bg-danger' %>">
            <%= link_to person_category.category.name, category_path(person_category.category), class: "link-light"%>
          </div>
        </td>
        <td>
          <% if person_category.money_transactions.any? %>
            <ul class="list-reset">
              <% person_category.money_transactions.order(important: :desc, created_at: :asc).each do |transaction|%> 
                <li>

                  <% if transaction.important %>
                    <i class="bi bi-exclamation-circle-fill text-danger"></i> 
                  <% else %>
                    <i class="bi bi-exclamation-circle-fill opacity-0"></i> 
                  <% end %>

                  <% if transaction.note%>
                    <i class="bi bi-sticky-fill"></i>
                  <% else%>
                    <i class="bi bi-sticky"></i>
                  <%end%>

                  <span class="badge bg-primary"><%=  transaction.amount_value %></span> 
                  <span> Date: <%=  transaction.created_at.to_formatted_s(:short) %> </span>
                  <%= link_to 'Update', edit_money_transaction_path(transaction) %> |
                  <%= link_to 'Delete', money_transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %> |
                  <%= link_to 'Details', money_transaction_path(transaction) %>
                </li>
              <%end%>
            </ul>
          <% else %>
            None
          <% end %>
        </td>
        <td>
          <% if person_category.category.transaction_type == 'Credit' %>
            - <%= person_category.money_transactions.sum(&:amount_value) %>
          <% else %>
            + <%= person_category.money_transactions.sum(&:amount_value) %>
          <% end %>
        <td>
      <tr>
      <% end %>
    </tbody>
  </table>
  <div>
   <ul class="list-reset">
    <li>*</li>
    <li><i class="bi bi-exclamation-circle-fill text-danger"></i> - important transaction</li>
    <li><i class="bi bi-sticky-fill"></i> - transaction with note </li>
    <li><i class="bi bi-sticky"></i> - transaction without note </li>
   </ul>
  </div>
<% else %>
  <p> No categories yet ... <p>
<% end %>

app/views/people/_form.html.erb
<div class="col-6">
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name of person", autofocus: true %>
  </div>

  <div class="form-group row mb-3">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group row mb-3 justify-content-start">
    <%= form.submit class: "btn btn-outline-success col-4" %>
  </div>
<% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Your persons</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td>
          <%= link_to 'Choose', person, class: "btn btn-outline-success" %>
          <%= link_to 'Edit', edit_person_path(person), class: "btn btn-outline-warning" %>
          <%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '<i class="bi bi-person-plus pe-3"></i> Add new person'.html_safe, new_person_path, class: "btn btn-outline-success"%>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<h1> Person details: </h2>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<h2> Categories </h2>

<%= render 'categories', obj: @person_categories %>

<%= link_to 'Edit person name', edit_person_path(@person) %> |
<%= link_to 'Back to people listing', people_path %>