config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :notes, except: %i[index show new]
  resources :money_transactions, except: %i[index]
  resources :categories, except: [:index]
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  resources :people
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'pages#home'

  get '/charts', to: 'charts#index'
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Finance tracker <i class="bi bi-coin"></i>'.html_safe, root_path, class: 'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Features</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Statistics'.html_safe, charts_path, class: "nav-link"%>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                [ <%= current_user.name %> ]
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to 'See your persons', people_path, class: "dropdown-item" %></li>
                <li><%= link_to 'Add new category'.html_safe, new_category_path, class: "dropdown-item"%></li>
                <li><%= link_to 'Add new transaction'.html_safe, new_money_transaction_path, class: "dropdown-item"%></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-danger dropdown-item" %></li>
              </ul>
            </li>
          <%end%>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<div class="row justify-content-center">
<div class="col-10">
    <% if flash.any? %>
    <% flash.each do |key, msg| %>
        <div class="alert <%= key == 'alert' ? 'alert-danger' : 'alert-success' %> alert-dismissible fade show" role="alert">
        <% if key == 'notice' %>
            <i class="bi bi-check-circle"></i>
        <% else %>
            <i class="bi bi-dash-circle"></i>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= msg %>
        </div>
    <% end %>
    <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppSqlite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container p-3">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>